name: Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    steps:
      - name: Récuperation du repo
        uses: actions/checkout@v2
      - name: Récupération du javascript
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install
        run: npm install
      - name: Exécution des tests
        run: npm test
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU Docker
        uses: docker/setup-qemu-action@v1
      - name: Install BuildX docker
        uses: docker/setup-buildx-action@v1
      - name: Connection à docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build et push mon image docker
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: chapeaumelon/weather:latest
